### PR TITLE
Fix rotations again

### PR DESCRIPTION
**Pull request by kujaku11**
This PR is to address issue #55 where rotations are currently set to rotate counterclockwise.  The correct rotation should be clockwise.  This seems to be a reoccurring issue and needs to be addressed properly so it doesn't' happen again, or at least there are some checks.  

- [x] Change rotation matrix to be clockwise positive [cos sin][-sin cos]
- [x] Update tests to test for correct rotation
  - [x] Rotation of Z
  - [x] Rotation of Tipper
- [x] Add documentation

### CODE REVIEW

**Comment by kujaku11** [comment]
@alkirkby I've update the rotation matrix and added tests to make sure the rotation is correct.  Can you have a look when you get a chance.  Rotation of Z and Tipper should be correct now, could you verify that they are correct now?

**Comment by alkirkby** [comment]
Cool, thanks for fixing- that seems to work now. 

One additional weird thing that might be worth addressing now is that the mt_object.rotation_angle just gets updated to the last angle that it was rotated to. And rotation angles are not read from file. So if I read in an MT object rotated to 115, I get mt_obj.rotation_angle = 0. 

Then if I read in an unrotated MT file and rotate by 115, I get mt_obj.rotation_angle=115. Then if I rotate by -115 I get mt_obj.rotation_angle = -115, where it should really be 0.

**Comment by kujaku11** [comment]
@alkirkby thanks, I need to have another look at the math to make sure that the rotations are proper, but good to hear it seems to work.  Just to confirm you are comparing rotation of a transfer function using mtpy and the geotools, and now they look the same?

Good catch, so what the rotation angle should do is update from the previous angle.  Like you say if you start out with 10 then rotate by 20, the rotation angle should be 30 instead of 20.  I can fix that too.  

As for reading in the rotation angle, I'll have a look at that as well.

**Comment by kujaku11** [comment]
@alkirkby or @kkappler Could you confirm the math here.  

For rotation of the impedance tensor we want to apply a similarity transformation so that the properties remain the same.  

We set the rotation matrix **R** to be the clockwise rotation matrix:

$$ \mathbf{R} = \begin{bmatrix}
\cos \theta & \sin \theta \\
-\sin \theta & \cos \theta 
\end{bmatrix}$$

Then if we formalize the similarity transformation as:

$$ \mathbf{A}' = \mathbf{R}^{-1} \mathbf{A} \mathbf{R}$$

We get rotation positive clockwise.  In that if we have an impedance tensor with a strike of zero and apply a rotation of 30 degrees the new strike is 30 degrees.  

If we formalize the similarity transformation as:

$$ \mathbf{A}' = \mathbf{R} \mathbf{A} \mathbf{R}^{-1}$$

Then we get rotation counter clockwise in that if we have a strike of 0 and apply a rotation of 30 degrees the new strike is -30.

So I think that the first similarity transform is the correct one unless others disagree.

**Comment by alkirkby** [comment]
> @alkirkby thanks, I need to have another look at the math to make sure that the rotations are proper, but good to hear it seems to work. Just to confirm you are comparing rotation of a transfer function using mtpy and the geotools, and now they look the same?
> 
> Good catch, so what the rotation angle should do is update from the previous angle. Like you say if you start out with 10 then rotate by 20, the rotation angle should be 30 instead of 20. I can fix that too.
> 
> As for reading in the rotation angle, I'll have a look at that as well.

Hi - yes that's right, I rotated an edi file in geotools, and compared it to the result in mtpy, and they were the same

**Comment by alkirkby** [comment]
> @alkirkby or @kkappler Could you confirm the math here.
> 
> For rotation of the impedance tensor we want to apply a similarity transformation so that the properties remain the same.
> 
> We set the rotation matrix **R** to be the clockwise rotation matrix:
> 
> R = [ cos ⁡ θ sin ⁡ θ − sin ⁡ θ cos ⁡ θ ]
> 
> Then if we formalize the similarity transformation as:
> 
> A ′ = R T A R
> 
> If we have an impedance tensor with a strike of zero and apply a rotation of 30 degrees the new strike is 30 degrees.
> 
> If we formalize the similarity transformation as:
> 
> A ′ = R A R T
> 
> Then if we have a strike of 0 and apply a rotation of 30 degrees the new strike is -30.
> 
> Which seems incorrect. I would think that if you rotate by a positive number then you should add that number to the existing strike angle. But maybe I'm wrong. @alkirkby can you confirm with this version of the branch that the rotation is the same as that from what you get from geotools?
> 
> From what I've seen in other codes is that they use the 2nd similarity transformation. that is what the current branch has.

Hi- yep that's right. Based on my testing yesterday I got the same.
According to Simpson and Bahr, the transform to rotate clockwise should be:
A ′ = R A R T

Yes I agree, if you rotate by a number then that number should be added to the strike (if it's negative it would be subtracted).

**Comment by kujaku11** [comment]
@alkirkby Great, thanks for the confirmation.  I'm still gonna do some testing and add some tests so that we can confidently say its correct.  

In Geotools can you estimate geoelectric strike?  Just curious what the strike angle is if you rotate say by 30.  Is the new strike angle plus 30?

**Comment by kujaku11** [comment]
@alkirkby, @kkappler So with the current formulation, that appears in nearly all MT basics 

$$Z_{rotated} = \mathbf{R} \mathbf{Z} \mathbf{R}^T$$

where:
$$ \mathbf{R} = \begin{bmatrix}
\cos \theta & \sin \theta \\
-\sin \theta & \cos \theta 
\end{bmatrix}$$

Now if we apply this with a positive angle we would expect that the new strike angle would be original + new.  However, it seems to be the opposite.  

For example if we have a general 2x2 matrix with a strike of 45:

$$ \mathbf{R} = \begin{bmatrix}
\sqrt{2} &  1\\
1 & \sqrt{2} 
\end{bmatrix}$$

Then rotate by 30 degrees:

$$ \mathbf{R} = \begin{bmatrix}
2.28 & .5 \\
.5 & .55 
\end{bmatrix}$$

the strike angle is now 15.  

Strike is calculated as 

$$\phi_{strike} = \dfrac{1}{2} \tan{\dfrac{a[0, 1] + a[1, 0]}{a[0, 0] - a[1, 1]}}$$

And even when I do this for a known model response I get the same, rotation counterclockwise

## Original data with a NE striking feature at depth
ne_faults_original

## Rotated by +30: expect the strike to rotate clockwise
ne_faults_rotatet_positive_30

So what I'm I missing here, is it how the strike angles are defined? But those are the same as what's in the literature.  Is it the reference frame that we are using to measure the angle from? Any thoughts would be helpful.

**Comment by kkappler** [comment]
@kujaku11 @alkirkby 

I committed a [notebook](https://github.com/MTgeophysics/mtpy-v2/blob/fix_rotations_again/docs/source/notebooks/rotations_conventions.ipynb) with some rotations notes that we can use as a starting point for conventions and maybe a tutorial in future.

There are a few conventions here, that I label in the notebook (coordinate frame, etc.).

There are two functions in the notebook that seem important `rotate_field_to_cardinal`, and `rotate_cardinal_to_field`, which are just inverses of each other.  

An excerpt, that may key in on the confusion:
image

Writing down the definition of the strike angle is would help to totally dial this in.

**Comment by alkirkby** [comment]
Thanks @kkappler, that clears things up nicely. We need to be careful when talking about strike and rotation angle. My earlier comment "Yes I agree, if you rotate by a number then that number should be added to the strike." is incorrect. What I should have said is ".....that number should be added to the **rotation angle**"

So, if an edi file is read in with a rotation angle of 0, then we rotate it by 30 degrees, then mtobj.rotation_angle goes from 0 to 30.
If the edi file is read in with a rotation angle of 30, then this information should be read into the mt object such that it also has a rotation angle of 30.

The way I see it, the strike of that mt object shouldn't change, no matter what the rotation angle. If our hypothetical mt object had a strike of 20, then we rotate it 30 degrees, the strike is now -10 (relative to our measurement frame) but it's still 20 degrees relative to north. So maybe we need to include rotation angle in our calculation of strike.

**Comment by kujaku11** [comment]
@alkirkby and @kkappler I updated a couple of things based on this conversation and the conventions laid out by Karl.

1. Added a property to the `MT` object `MT.coordinate_reference_frame` which can be set to `ned` (default) or `enu`.  This value is pulled from the `MT.station_metadata.transfer_function.sign_convention` if that value is unknown its set to `ned`.  If the `MT.coordinate_reference_frame` is `ned` the rotation matrix used is the conventional counter-clockwise rotation matrix that Karl showed is the correct one.  If `enu`, then the clockwise rotation matrix is used.  Therefore, the use has the flexibility to pick their reference frame.
2. Updated the `MT.rotation_angle` to be additive when a rotation is set.  
3. Updated the notebook to demonstrate the listed changes.
4. Added a few tests, but should add some more, if folks agree with the changes. If these changes are ok then I'll add similar functionality to `MTData`.

**Comment by alkirkby** [comment]
@kujaku11 @kkappler 
Hold on, I am confused now. In Simpson and Bahr, the matrix 

$$ \mathbf{R} = \begin{bmatrix}
\cos \theta & \sin \theta \\
-\sin \theta & \cos \theta 
\end{bmatrix}$$

Should rotate a point clockwise (x toward y). So is this the matrix that is used if we use ned?

**Comment by kujaku11** [comment]
@alkirkby Yup, that is where the confusion is. Karl's notebook demonstrates that in an ned coordinate system the rotation matrix is the conventional counter-clockwise rotation matrix. Which is not what is in bahr or nearly all other mt papers. 

So what is it that we are missing for a ned coordinate system to use the clockwise rotation matrix?

**Comment by kkappler** [comment]
> @kujaku11 @kkappler Hold on, I am confused now. In Simpson and Bahr, the matrix
> 
> R = [ cos ⁡ θ sin ⁡ θ − sin ⁡ θ cos ⁡ θ ]
> 
> Should rotate a point clockwise (x toward y). So is this the matrix that is used if we use ned?

Hi @alkirkby  

Turning to page 82 of Simpson & Bahr, Figure 5.2 shows a rotation of alpha mapping x→x’, with x moving towards y.  This is consistent with Convention 1 in the notebook (but a way clearer diagram than what I showed)
image


They say… “Theoretically we can simulate a field suite setup with sensors oriented in any direction $\alpha$ …”

Based on that, I interpret the “simulating of data acquired at $\alpha$” as being a rotation _from_ cardinal, _to_ field-deployed-coordinates.  That would correspond to the transformation in the notebook `rotate_cardinal_to_field`, which returns `rotate_field_to_cardinal(Zc, -theta)`, i.e. the transpose of the rotation matrix.  i.e. Simpson and Bahr Equation 5.2 defines the matrix that rotates an impedance tensor in the cardinal frame to one that would have been observed if the sensors were deployed rotated by + $\alpha$.  So this is consistent with the transformations in the notebook, but not easy to follow.

FWIW I think that 80% of the confusion comes from the fact that we are rotating a tensor, (which is done by rotating the E, H separately).  Rotating E, H is pretty intuitive, rotating the tensor, not so much.

The tensor rotation depends on the coordinate frame you started in.  I defined in the notebook
- $Z_c = RZR^T$
- $Z = R^TZ_c R$
In this case, my $R$ rotated the vectors +ve $\alpha$, so what I call $R^T$ is Simpson and Bahr's $\beta$. i.e. To get field from cardinal, I would have to use 
 $Z = R^TZ_c R$,  which would be $\beta Z_c \beta^T$, according to S&B.

**Comment by kujaku11** [comment]
@alkirkby , @kkappler That's a good question.   I would try using this branch and use the following code.  And maybe try the same with Geotools and see which one looks correct.  This is my confusion as well.  So it would be nice to get some verification.  

```python
from mtpy import MT

m1 = MT()
m1.read(r"edi_file")
m1.coordinate_reference_frame = "ned"

m_rot_ned = m1.rotate(110, inplace=False)

m1.coordinate_reference_frame = "enu"

m_rot_enu = m1.rotate(110, inplace=False)

m_rot_ned.plot_phase_tensor(fig_num=1)
m_rot_enu.plot_phase_tensor(fig_num=2)
```

The correct one should have a strike of 0 in the new reference frame.

**Comment by alkirkby** [comment]
Hi @kujaku11 -
Just pulled the latest updates and tested.
Confirming that if I run the following:

mto_unrotated = MT()
mto_unrotated.from_edi('unrotated edi file')
mto_unrotated.coordinate_reference_frame = "ned"
mto_unrotated.rotate(101)

mto_rotated = MT()
mto_rotated.from_edi('edi file rotated to 101 degrees in geotools')

The impedances of the two objects are the same (within 1e-6). Note there is a difference as mto_unrotated.Z.z seems to be rounded to 4-6 d.p.?

The new rotation angle of mto_unrotated after rotation is 101, so that seems correct. 

Two comments:
- The rotation angle of the mto_rotated read in from file is not read from file
- The code throws an error if I don't set mto_unrotated.coordinate_reference_frame. Would it be better to have a default set so the user doesn't have to set this? If I hadn't read @kkappler's notebook I would have no idea what ned or enu are.

**Comment by kujaku11** [comment]
Great, at least there is confirmation that we are doing the correct rotation. 

1. I'll have a look at the rotation angle read from a file. That is in mt-metadata.

2. The default should be ned, but your probably right there should be some more obvious option. I'll work on the logic for making sure there is a default value always set. Could you post the header of the file you read in? Just curious why it didn't set the default value.

**Comment by alkirkby** [comment]
Hi @kujaku11 I don't know if I can post the whole header as it's confidential data - was there a field in there that I can check for?

**Comment by kujaku11** [comment]
@alkirkby no problem. Is there any type of sign convention parameter in the header or notes section?

**Comment by kujaku11** [comment]
@alkirkby Can you pull the main branch of mt-metadata and confirm that the rotation angles are being pulled from the EDI file into the MT object correctly? 

I also changed the logic so that the `coordinate_reference_frame` is default `NED` but add other options that may make sense to the user.  See the doc string for `MT` if you want more options.  But under the hood there are only 2 NED or ENU.  I added a warning if the user sets to ENU cause if you assume that coordinate reference frame then the phase tensor, and plots will likely be incorrect and I'm not going to accommodate ENU at this time.  

If that works I'll make this pull request live for you and Karl to review.

**Comment by alkirkby** [comment]
Hmm, I think I have mt-metadata installed through conda and not git. Is there a branch of mtpy I can pull that will do this? Or should I install mt-metadata and somehow link it to mtpy?

**Pull request merged**
