### PR TITLE
Occam2d fixes

### PR DESCRIPTION
**Pull request by alkirkby**
Various updates to Occam2d so that it works and gives correct results. Seems to be failing tests when building environment for testing. Not sure why.

### CODE REVIEW

**Comment by alkirkby** [comment]
OK- got the env to load ok. Will look into failing tests.

**Comment by kujaku11** [comment]
@alkirkby looks like we just need to change the number of significant digits in the test, maybe something like 5 sig figs.  

Looks like the tests are

**Comment by kujaku11** [comment]
@alkirkby, I updated the tests so they pass.

**Comment by alkirkby** [comment]
Awesome thank you @kujaku11 and sorry I didn't get to this. I did change some things in generate_profile so that the 0 point in the profile is a perpendicular projection of the first site, I hope that didn't break anything else.

**Pull request merged**
